title: Ripunjay Singh
logo: /headshot2.jpeg
description: I am currently pursuing my MS in Cybersecurity at NYU Tandon. As an AI/ML Engineer Intern at LTIMindtree, I am building an insurance risk analytics system. I am also investigating software supply chain risks with DTCC and NYU. I excel in tools like Splunk and Tableau, and I am passionate about tackling contemporary cybersecurity challenges through novel ways like AI, ML. 
show_downloads: false
theme: jekyll-theme-minimal
