title: Ripunjay Singh
logo: /headshot.png
description: I am currently pursuing my MS in Cybersecurity at NYU Tandon School of Engineering. As an AI/ML Engineer Intern at LTIMindtree, I am developing an insurance risk analytics system to provide actionable risk insights. I am also working with DTCC and NYU to discover software supply chain risks in open-source software. I thrive on mastering tools like Splunk and Tableau, and I am passionate about diving deep into Firewalls and SIEM tech. From tackling vulnerability puzzles to cloud security challenges, I am always seeking the next big cybersecurity adventure to push my boundaries in this dynamic field.
show_downloads: true
theme: jekyll-theme-minimal
